### ISSUE TITLE
Test suite of Hotel Booking and date

### ISSUE THREAD

**Issue by AnnaMaks** [IrynaMaksymenko/hotel-booking#4]

**Comment by IrynaMaksymenko** [comment]
Потрібно ще протестувати:
- ті запити які тільки для адміна не працюють для звичайного юзера
- ті запити що для всіх юзерів працюють і для адміна і для звичайного юзера
- ніякі запити не працюють без авторизації
- і по функціоналу можна придумати більше заплутаних юз кейсів, наприклад:
    - якщо всі кімніти готелю вже забукані на задану дату, то getFreeRooms
має повернути пустий список
    - якщо є забукана кімната на 12.01-13.01 і на 14.01 - 15.01 то на
період 12.01-15.01 нема вільних кімнати але на 13.01-14.01 є вільна кімната
    - якщо кімната вже є забукана але юзер (той чи інший) вседно букає її
знову, то має повернутись 400
